#!/bin/bash
# Q KB Explorer — Entrypoint with optional TLS
# Mount certs to /app/certs/ or set QKBE_TLS_CERT / QKBE_TLS_KEY env vars

# ── Credential Vault Initialization ──────────────────────────────────────
# Create key and data directories with restrictive permissions.
# The encryption key is auto-generated by the app on first API call.
# Key and vault are on separate volumes for defense in depth:
#   -v qkbe-keys:/keys   (hidden .vault_key.bin, 0400)
#   -v qkbe-data:/data    (encrypted vault.json + qkbe.db, 0600)
mkdir -p /keys /data
chmod 700 /keys /data
echo "[QKBE] Credential vault directories ready (/keys, /data)"
if [ -f /keys/.vault_key.bin ]; then
    echo "[QKBE] Encryption key found — vault operational"
else
    echo "[QKBE] No encryption key — will generate on first credential save"
fi

# SQLite database
if [ -f /data/qkbe.db ]; then
    echo "[QKBE] SQLite database found at /data/qkbe.db"
else
    echo "[QKBE] No database yet — will create on first startup"
fi

CERT="${QKBE_TLS_CERT:-/app/certs/server.crt}"
KEY="${QKBE_TLS_KEY:-/app/certs/server.key}"
BIND="${QKBE_BIND:-0.0.0.0}"
PORT="${QKBE_PORT:-5000}"
WORKERS="${QKBE_WORKERS:-1}"

# Single worker: sync progress lives in-memory — multiple workers would
# cause progress/details requests to miss the worker running the sync thread.
# Timeout 660s > longest sync page timeout (600s for QIDs) so gunicorn
# doesn't kill the worker mid-sync.
GUNICORN_ARGS="--bind ${BIND}:${PORT} --workers ${WORKERS} --timeout 660 --preload app.main:app"

if [ -f "$CERT" ] && [ -f "$KEY" ]; then
    echo "[QKBE] TLS enabled — cert: $CERT  key: $KEY"
    GUNICORN_ARGS="--certfile ${CERT} --keyfile ${KEY} ${GUNICORN_ARGS}"
    export QKBE_TLS_ENABLED=1
    echo "[QKBE] Listening on https://${BIND}:${PORT}"
else
    echo "[QKBE] No TLS certs found — running plain HTTP"
    echo "[QKBE] To enable TLS: mount certs to /app/certs/ or set QKBE_TLS_CERT/QKBE_TLS_KEY"
    echo "[QKBE] Listening on http://${BIND}:${PORT}"
fi

exec gunicorn $GUNICORN_ARGS
